// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TsKids.Infrastructure.Data;

#nullable disable

namespace TsKids.Infrastructure.Migrations
{
    [DbContext(typeof(TsKidsDbContext))]
    partial class TsKidsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TsKids.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Réplicas de Ferrari, Lamborghini, McLaren e outras supercars lendárias",
                            ImageUrl = "https://picsum.photos/seed/supercar/400/300",
                            Name = "Supercars"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Réplicas de Land Rover, Range Rover, Mercedes GLE e outros SUVs",
                            ImageUrl = "https://picsum.photos/seed/suv4x4/400/300",
                            Name = "SUVs e 4x4"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Réplicas de Porsche 911, Volkswagen Fusca, Mini Cooper e ícones clássicos",
                            ImageUrl = "https://picsum.photos/seed/classic/400/300",
                            Name = "Clássicos"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Description = "Réplicas de BMW, Honda e Harley-Davidson para os pequenos pilotos",
                            ImageUrl = "https://picsum.photos/seed/moto/400/300",
                            Name = "Motos Elétricas"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Description = "Capacetes, coletes de segurança, pistas e acessórios para carrinhos elétricos",
                            ImageUrl = "https://picsum.photos/seed/acessorio/400/300",
                            Name = "Acessórios"
                        });
                });

            modelBuilder.Entity("TsKids.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Brand = "Ferrari Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3006),
                            Description = "Réplica oficial licenciada da Ferrari SF90 Stradale em versão infantil. Motor elétrico 12V com velocidade máxima de 5 km/h. Controle remoto parental incluso, faróis de LED, som do motor real gravado, assento em couro ecológico e cinto de segurança. Indicado para crianças de 3 a 8 anos.",
                            ImageUrl = "https://picsum.photos/seed/ferrari/400/500",
                            Name = "Ferrari SF90 Elétrico Infantil",
                            Price = 3499.90m,
                            Stock = 7,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3006)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Brand = "Lamborghini Junior",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3017),
                            Description = "Réplica do Lamborghini Huracán com pintura exclusiva amarela. Duas velocidades (3 e 5 km/h), abertura de portas no estilo tesoura, painel digital funcional, conexão Bluetooth para música e controle remoto 2.4GHz para os pais. Suporta até 35 kg.",
                            ImageUrl = "https://picsum.photos/seed/lambo/400/500",
                            Name = "Lamborghini Huracán 12V",
                            Price = 4199.00m,
                            Stock = 4,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3017)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Brand = "McLaren Junior",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3061),
                            Description = "Réplica do McLaren 720S com capota retrátil elétrica. Motor 12V duplo (tração nas 4 rodas), velocidade até 6 km/h, suspensão real, pneus de borracha e carregador incluso. O presente favorito da temporada para crianças de 4 a 9 anos.",
                            ImageUrl = "https://picsum.photos/seed/mclaren/400/500",
                            Name = "McLaren 720S Spider Kids",
                            Price = 4899.00m,
                            Stock = 3,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3061)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Brand = "Range Rover Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3066),
                            Description = "Réplica do Range Rover Evoque com tração 4x4 real. Motor duplo 12V, 3 marchas para frente e 1 ré, suspensão amortecida, tela MP3 com Bluetooth, faróis e lanternas de LED e controle remoto parental. Até 40 kg. Ideal para 3 a 10 anos.",
                            ImageUrl = "https://picsum.photos/seed/rangerover/400/500",
                            Name = "Range Rover Evoque Infantil 12V",
                            Price = 2999.90m,
                            Stock = 9,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3066)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Brand = "Mercedes Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3069),
                            Description = "O queridinho das crianças! Réplica do Mercedes GLE AMG com dois assentos (leva dois pequenos pilotos). Bateria 24V, velocidade até 8 km/h, câmera de ré, tela touch, som do motor V8 AMG e pneus com perfil off-road.",
                            ImageUrl = "https://picsum.photos/seed/mercedesgle/400/500",
                            Name = "Mercedes-Benz GLE AMG 4x4",
                            Price = 5499.00m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3069)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Brand = "Porsche Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3073),
                            Description = "Réplica do icônico Porsche 911 anos 70 em versão elétrica infantil. Design clássico fiel ao original, motor 6V, velocidade suave de 3 km/h ideal para os menores, rodas de liga, faróis retrô e buzina. Para crianças de 2 a 5 anos.",
                            ImageUrl = "https://picsum.photos/seed/porsche911/400/500",
                            Name = "Porsche 911 Clássico 6V",
                            Price = 1899.00m,
                            Stock = 11,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3073)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            Brand = "Mini Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3076),
                            Description = "Réplica do Mini Cooper S com visual retrô e personalizações exclusivas. Motor 12V, velocidade de 4 km/h, tejadilho com union jack, rodas cromadas e banco de couro ecológico. Umas das réplicas mais charmosas do mercado.",
                            ImageUrl = "https://picsum.photos/seed/minicooper/400/500",
                            Name = "Mini Cooper S Elétrico Retrô",
                            Price = 2299.00m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3076)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            Brand = "BMW Motorrad Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3079),
                            Description = "Réplica da BMW S1000RR, a moto esportiva mais famosa do mundo em miniatura elétrica. Motor 6V, rodas de treinamento removíveis, faróis de LED, sons da BMW e velocidade até 4 km/h. Para crianças de 3 a 7 anos.",
                            ImageUrl = "https://picsum.photos/seed/bmwmoto/400/500",
                            Name = "BMW S1000RR Moto Infantil 6V",
                            Price = 1299.00m,
                            Stock = 14,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3080)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            Brand = "Harley Kids",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3083),
                            Description = "Réplica da lendária Harley-Davidson Fat Boy em versão infantil. Estilo chopper autêntico, motor 12V, banco duplo, rodas largas cromadas, som do motor Harley original e velocidade de 3 km/h. Para os pequenos que já nasceram com DNA de liberdade.",
                            ImageUrl = "https://picsum.photos/seed/harley/400/500",
                            Name = "Harley-Davidson Fat Boy Elétrica",
                            Price = 1799.00m,
                            Stock = 6,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3084)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            Brand = "TsKids Gear",
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3086),
                            Description = "Capacete homologado para uso em carrinhos elétricos infantis. Material ABS resistente, viseira anti-risco, interior acolchoado lavável e regulagem de tamanho. Disponível em vermelho, amarelo, azul e preto. Tamanhos P, M e G.",
                            ImageUrl = "https://picsum.photos/seed/capacete/400/500",
                            Name = "Capacete Infantil Piloto Pro",
                            Price = 189.90m,
                            Stock = 40,
                            UpdatedAt = new DateTime(2026, 3, 24, 14, 3, 26, 868, DateTimeKind.Utc).AddTicks(3087)
                        });
                });

            modelBuilder.Entity("TsKids.Domain.Entities.Product", b =>
                {
                    b.HasOne("TsKids.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TsKids.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
